<?php

$contact_our_office = '<p>Please <a href="/contact/">contact my office</a> for a free case evaluation. </p>';
$situations = array(
"Falls" => "<p>Falls are the leading cause of fatal injury in geriatric patients. According to a study published in 2015 in the Archives of Gerontology and Geriatrics journal, nursing home falls occur at twice the rate of community falls. Information obtained from the Center for Disease Control (<abbr>CDC</abbr>) suggests that between 50% and 75% of nursing home residents fall each year.  Residents often fall more than once, and about 35% of fall injuries occur among residents who cannot walk. As high as 20% of nursing home falls cause serious injuries, and 2% to 6% cause fractures.  The law requires facilities to examine risk factors that cause falls and accidents and take steps to limit risks by keeping the resident environment as free of accident hazards as possible, giving each resident adequate supervision and using assistive devices to prevent accidents (42 CFR 483.25(h)).   But facilities must be proactive in order to limit risk successfully.  Interestingly, the <abbr>CDC</abbr> reports that restraints do not help prevent falls.  Increased risk of falls in older persons is associated with muscle weakness, gait problems, wet floors, poor lighting, incorrect bed height, improperly fitted wheelchairs, certain medicines, poor foot care, poorly fitting shoes, improper or incorrect use of walking aids, inattentive staff and low staff-to-resident ratios.  If your loved one has suffered a fall(s) at a long-term care facility, it may be a sign that the facility breached the standard of care or failed to prevent the fall when it should and could have.</p>",

"Bedsores" => "<p>Bedsores (also known as decubitus ulcers, pressure ulcers, or pressure sores) are one of the most common injuries in long-term care facilities.  Information obtained from the Center for Disease Control (<abbr>CDC</abbr>) suggests that approximately 1 in 10 nursing home residents have had a bedsore.  Bedsores develop when a resident is left in one position for too long and commonly form where bones are close to skin, such as the heel, ankle, tailbone, hip, shoulder, back, elbow, and back of the head.  Left unchecked, serious infection can develop, resulting in amputation, sepsis, or death.  The law requires facilities to be proactive in preventing bedsores (42 CFR 483.25(c)).  This can be accomplished by implementing and maintaining proper prevention protocol that includes keeping skin clean and dry, changing position, and using pillows and products that relieve pressure.  The law also requires facilities to have sufficient staff to perform these services adequately (42 CFR 483.30).  If your loved one is developing bedsores, it may be a sign that the facility is neglecting its duties or not providing the appropriate level of care.</p>",

"Medication Errors" => "<p>Information obtained from the Center for Disease Control (<abbr>CDC</abbr>) suggests that adverse drug events—injury resulting from the use of medication—result in over 700,000 visits to hospital emergency departments, and nearly 120,000 patients each year need to be hospitalized for further treatment after such visits.  The <abbr>CDC</abbr> reports 82% of American adults take at least one medication and 29% take five or more.  The majority of nursing home residents are elderly and frail and require numerous medications according to the <abbr>CDC</abbr>.  Not all adverse drug events constitute a medication error, which can be defined as any preventable event that may cause or lead to inappropriate medication use or patient harm while the medication is in the control of the health care professional, patient, or consumer.</p>

<p>However, according to a study published in the journal of Quality and Safety in Healthcare (2007), the most common medical errors in long-term care facilities were dose omission (32%), underdose (7%), wrong patient (6%), wrong product (6%), and wrong strength (6%).  The study revealed that medication errors most commonly occurred during medication administration (47%) or documentation (37%), with a smaller number related to dispensing (11%), monitoring (3%) and prescribing (2%).  The most commonly reported cause was basic human error (48%), followed by transcription error (18%), and poor communication (4%).  Licensed practical nurses were the most common category of primary personnel implicated in the error (59%), followed by registered nurses (22%), support personnel (11%), pharmacists (6%), and medication aides (1%), and physicians (1%).  Of the primary personnel implicated in the error, 92% were permanent regular staff.  Approximately 87% of errors had no observed negative medical effect on the patient.  Seven drugs were involved in almost a third of all errors:  lorazepam (anxiety) (6%), oxycodone (pain) (5%), warfarin (anticoagulant) (4%), furosemide (fluid retention) (3%), hydrocodone (pain) (3%), insulin (diabetes) (3%), and fentanyl (pain) (3%).  According to a 2013 article published by the Institute for Safe Medication Practices, many medication errors occur during transitions between hospitals and long-term care facilities due to lapse of communication among facility staff along with documentation and transcription errors.  </p>

<p>The law requires facilities to be proactive in preventing medication errors (42 CFR 483.25(m)), which can occur during prescription processing, dispensing and delivery, administration of medications by nursing facility personnel, ongoing medication management, and return/re-use and disposal of unused medications.  The law also requires facilities to have sufficient staff to perform these services adequately (42 CFR 483.30).  If your loved one has suffered signs of medication error, been hospitalized or even died from a medication error such as overdose, the facility may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Infections" => "<p>Infections are one of the most common causes of death in long-term care facilities.  One to three million serious infections occur every year in long-term care facilities according to information obtained from the Center for Disease Control (<abbr>CDC</abbr>).  According to a study published in Aging Health journal, in 2011, pneumonia, urinary tract, diarrheal illnesses, and skin and soft tissue infections are the most common endemic infections among nursing home residents. The <abbr>CDC</abbr> reports as many as 380,000 residents die each year of such infections.</p>

<p>Prevention of infection includes early identification and containment, appropriate cleaning/disinfection of equipment and the environment, hand hygiene, and the appropriate selection and use of antibiotics.   The law requires facilities to implement these preventative measures to protect residents.  For example, the facility “must establish and maintain an infection control program designed to provide a safe, sanitary, and comfortable environment and to help prevent the development and transmission of disease and infection” (42 CFR 483.65). Facilities must be proactive in order to prevent infection effectively.  If your loved one has suffered from infection, been hospitalized or even died from infection, the facility may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Wrongful Death" => "<p>Family members must make extremely difficult decisions when deciding whether to place their loved one in a long-term care facility.  Imagine the guilt and grief when it is discovered that mom or dad or grandma or grandpa passed away under a roof of quiet, consistent abuse or neglect by the very facility that promised to take care of them just like family.  Wrongful death lawsuits should be principled actions that not only hold parties responsible for their broken promises but also address threats to our community.  Many long-term care facilities are owned by large parent companies that are more concerned about profits than people.  This is wrong, morally and legally.  The Center for Disease Control (<abbr>CDC</abbr>) reports that in 2014, in the U.S., there were 1.4 million long-term care residents and 1.7 million licensed beds.  These numbers are steadily increasing as the baby boomer generation ages and for-profit facilities—excited about this growing demographic—expand.  </p>

<p>Wrongful death cases require certain procedural steps to be taken before filing suit, and sometimes after a lawsuit has been filed, if the resident passes during litigation.  There are special issues with wrongful death cases that warrant careful consideration.  And, wrongful death cases often require certain strategic choices, early on, in order to get the case into the best posture for trial.  Wrongful death is avoidable death.  Data collected by the National Center on Health Statistics lists starvation, dehydration, and bedsores as common causes of death in long-term care facilities, but there are numerous reasons why avoidable deaths occur in such facilities.  A long-term care facility, like a hospital, must never expose its residents to needless danger, much less death.  Without a review of the medical and facility records by a medicolegal expert, it is sometimes very difficult, if not impossible, to discern whether the death of a loved one was avoidable and therefore wrongful.</p>",

"Dehydration" => "<p>After oxygen, water is the nutrient most needed for life.  Approximately 60% of the adult human body is water.  Dehydration is the failure to maintain adequate amounts of body water because of either poor fluid intake or pathologic loss of body fluids.  A study published in Clinical Nursing Research journal, in 2003, found that the 6-month incidence of dehydration in nursing home residents was as high as one in three.  Dehydration is a major cause of decreased attention and fluctuating mental states, the hallmarks of delirium, in long-term care facilities according to a 2015 article in the Journal of the American Medical Directors Association.  Extreme cases of dehydration can result in hospitalization or death.  One-third of nursing home residents are unable to eat and drink on their own, which is one reason why it is critical that long-term care facilities are adequately staffed.  Further, facility staff must be adequately trained to identify signs of dehydration and prevent dehydration because older persons are at increased risk of dehydration.  The main reason why is that as older persons become dehydrated, they fail to develop thirst at the same rate as younger persons.  With aging, there is a decline in the kidneys to retain fluid.  Additionally, decline in muscle mass is associated with aging (muscle is the major water storage organ in the body).  Other reasons include frequent urination and excessive thirst (associated with higher prevalence of diabetes in older persons), increase of polypharmacy (use of four or more medicines), and particularly diuretics (medicines that promote the production of urine) to treat ankle edema (swelling), and excess sweating and hyperventilation associated with COPD (lung disease).</p>

<p>The best defense against dehydration is prevention. Preventing dehydration includes keeping a list of residents at high risk of dehydration at the nurse’s station and other strategic locations, routinely monitoring signs of dehydration (for example, cracked lips, dry oral mucous, poor skin turgor, dark urine), establishing appropriate hydration goals and protocols such as scheduling fluid administration at least three times a day between meals, offering attractive liquids such as flavored water (with mint leaves, lemon, or orange zest) on a beverage cart, liquid-rich fruits and vegetables (watermelon, cucumber, etc.), sponsoring cocktail hour (avoiding beverages with caffeine or alcohol since they have dehydrating properties) or arranging for residents to eat meals and have snacks together with other residents (residents typically consume more food and liquids in a social setting), asking residents for their ideas on delicious drink ideas, offering at least a full glass of liquid with medications (studies show that residents tend to drink the entire amount of fluid offered), making long, flexible straws available as needed for certain residents, and providing residents with personal water bottles on field trips.  Finally, CNAs can offer small amounts of fluid every time they interact with a resident during care delivery; i.e., toileting, after a transfer, after getting dressed, etc.</p>

<p>The law requires facilities to implement preventative measures like these to protect residents from dehydration (42 CFR 483.25(j)), but facilities must be proactive in order to do so successfully.  The law also requires facilities to have sufficient staff to perform these services adequately (42 CFR 483.30).  If your loved one has suffered signs of dehydration, been hospitalized or even died from dehydration, the facility or nursing staff may have neglected their duties or failed to provide the appropriate level of care.</p>",

"Malnutrition" => "<p>An essential nutrient is a substance that must be obtained from the diet because the body cannot make it in sufficient quantity to meet its needs (water, protein, carbohydrates, fat, vitamins and minerals).  Malnutrition is defined as lack of proper nutrition caused by not having enough to eat, not eating enough of the right things, or being unable to use the food that one does eat.  According to a study published in the Current Opinion in Clinical Nutrition and Metabolic Care journal in 2014, approximately 20% of nursing home residents had some form of malnutrition.  The researchers also found that mortality was the major consequence of malnutrition among nursing home residents, whereas higher BMIs had lower risks of mortality.  Apart from mortality, the Mayo Clinic reports that malnutrition in older persons can lead to various health concerns including a weak immune system, which increases the risk of infections, prolonged wound healing, and muscle weakness, which can lead to falls and fractures.  Additionally, malnutrition can lead to further disinterest in eating or lack of appetite, which only makes the problem worse.</p>

<p>One-third of nursing home residents are unable to eat and drink on their own, which is one reason why it is critical that long-term care facilities are adequately staffed.  Further, facility staff must be adequately trained to identify signs of malnutrition and prevent malnutrition because older persons are at increased risk of malnutrition.  Reasons for the increased risk include health problems associated with aging, which are connected with loss of appetite such as depression, dementia, or trouble eating.  Also, older persons often have certain dietary restrictions such as limits on salt, fat, protein, or sugar that may contribute to inadequate eating.  Signs of malnutrition include weight loss, poor wound healing, easy bruising, and dental difficulties.</p>

<p>The law requires facilities to implement preventative measures to protect residents from malnutrition (for example, serving food attractively, preparing food in a form designed to meet individual needs, offering substitutes of similar nutritive value to residents who refuse served food (42 CFR 483.35(d)), but facilities must be proactive in order to prevent malnutrition successfully.  The law also requires facilities to have sufficient staff to perform these services adequately (42 CFR 483.30).   If your loved one has suffered signs of malnutrition, been hospitalized or even died from malnutrition, the facility may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Asphyxiation" => "<p>Asphyxia or asphyxiation is severely deficient supply of oxygen to the body that arises from abnormal breathing.  An example of asphyxia is choking.  Asphyxia can result in hypoxia (oxygen deprivation), which affects primarily the tissues and organs.  Tooth loss is a risk factor for foreign-body asphyxiation in nursing home residents according to a study published in the 2012 issue of Archives of Gerontology and Geriatrics journal.  According to a study published in Geriatric Nursing in 1999, dysphagia or trouble swallowing is another risk factor among nursing home residents.  Residents with dementia or Alzheimer’s disease, for example, cannot eat safely on their own.  Another risk factor includes use of bed rails.  A 2009 article published in The American Journal of Forensic Medicine and Pathology reports that lethal asphyxial entrapment between bedrails and mattresses is a well-recognized clinical event despite few descriptions of autopsy findings.  Residents with tracheostomies are at greater risk of asphyxiation as well.  A tracheostomy is a surgically created hole through the front of the neck and into the windpipe.  A tube is usually placed through this opening to provide an airway and to remove secretions from the lungs.</p>

<p>Signs of generalized hypoxia include dizziness, confusion, hallucinations, severe headaches, reduced consciousness, tachycardia (fast heart rate), cyanosis (blue or purple coloration), bradycardia (slow heart rate), low blood pressure and death.  The best defense against asphyxiation is prevention.  The law requires facilities to implement preventative measures to protect residents from asphyxiation.  For example, a facility “must provide special eating equipment and utensils for residents who need them” (42 CFR 483.35(g).  Another example that the law specifically addresses is “complicated feeding problems” such as “difficulty swallowing”  (42 CFR 483.35((h)(3).  Additionally, a facility “must ensure that residents receive proper treatment and care for…tracheostomy care … tracheal suctioning … and … respiratory care”  (42 CFR 483.25(k). Despite these regulations and others, facilities must be proactive in order to prevent asphyxiation.  The law also requires facilities to have sufficient staff to perform these services adequately (42 CFR 483.30).  If your loved one has suffered signs of asphyxiation, been hospitalized or even died from asphyxiation, the facility may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Poor Hygiene / Understaffing" => "<p>Poor hygiene may be the quickest way to identify an understaffed nursing home or assisted living facility because an adequately staffed facility should not smell bad.  Nurse staffing levels are too low in 50% of U.S. nursing homes, according to a 2016 study published in the Health Services Insights journal titled “The Need for Higher Minimum Staffing Standards in U.S. Nursing Homes.”  The study’s authors cite numerous studies that document “a strong positive impact of nurse staffing on both care process and outcome measures.”  Additionally, they report that 70% of U.S. nursing homes are for-profit facilities with an orientation to maximizing profits for owners and shareholders, and that profit incentive has been shown to be directly related to low staffing.  Facilities with the highest profit margins have been found to have the poorest quality according to a study published in the Medical Care journal (2013).</p>

<p>Poor hygiene is associated with infection and other medical problems.  For example, nursing home residents who did not receive oral care were more than three times more likely to die of nursing-home associated pneumonia than residents who did according to a study published in the Journal of the American Geriatrics Society in 2008.  Many diseases and conditions can be prevented or controlled through appropriate hygiene according to the Center for Disease Control (<abbr>CDC</abbr>).  The law requires facilities to implement preventative measures to protect residents from poor hygiene.  For example, a facility “must ensure that a resident who is unable to carry out activities of daily living receives the necessary services to maintain good nutrition, grooming, and personal and oral hygiene” (42 CFR 483.25(a)(3).  If your loved one has suffered from poor hygiene, or suspect that he or she was hospitalized or even died from medical problems caused by poor hygiene, the nursing staff may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Sexual Abuse" => "<p>Acts of sexual abuse against older residents in nursing homes is difficult to imagine because sexuality in older age is still taboo; it is hard to believe it occurs.  The fact that staff are not aware that it could happen, or have a hard time believing that it actually happens, can amplify residents’ vulnerable positions as potential victims of sexual abuse, and makes it even more challenging to report or uncover such acts according to a 2015 study published in Nursing Research and Practice journal.  Sexual abuse against older persons is underreported according to some studies.  An example of this may be a 2010 study published in the American Journal of Public Health, which reports that less than one percent of older persons are exposed to sexual abuse.</p>

<p>If you suspect that your loved one has been the victim of sexual abuse involving another resident, the facility may have neglected its duties or failed to provide the appropriate level of care.  Sexual abuse implicating facility staff would be a heinous breach of trust and an obvious example of substandard care, which may also subject the facility to punitive damages, which are damages exceeding simple compensation and awarded to punish the defendant.</p>",

"Sepsis" => "<p>According to the Mayo Clinic, sepsis is a potentially life-threatening complication of an infection, which occurs when chemicals released into the bloodstream to fight the infection trigger inflammatory responses throughout the body.  This causes a cascade of changes that can damage multiple organs, causing them to fail.  If sepsis progresses to septic shock, blood pressure can drop dramatically leading to death.  The Mayo Clinic adds that anyone can develop sepsis, but it’s common and most dangerous in older adults or those with weakened immune systems.  Early treatment of sepsis, usually with antibiotics and large amounts of intravenous fluids, improves chances for survival.</p>

<p>Older adults and particularly nursing home residents have a disproportionately high incidence of and morbidity from severe sepsis according to a 2013 study published in the Journal of Critical Care.  The study revealed that older adults (aged 65+) were 5-fold more likely to have infections classified as severe sepsis than younger adults (6.5% vs. 1.3%), and nursing home residents were 7-fold more likely to have a severe sepsis diagnosis compared with non-nursing home residents (14% vs. 1.9%).  Further, nursing home residents with severe sepsis, compared with non-nursing home residents had significantly higher rates of in-hospital mortality (37% vs. 15%).</p>

<p>Prevention of infection includes early identification and containment, appropriate cleaning/disinfection of equipment and the environment, hand hygiene, and the appropriate selection and use of antibiotics.   The law requires facilities to implement these preventative measures to protect residents.  For example, the facility “must establish and maintain an infection control program designed to provide a safe, sanitary, and comfortable environment and to help prevent the development and transmission of disease and infection” (42 CFR 483.65).  But facilities must be proactive in order to prevent sepsis successfully.  If your loved one has been hospitalized or even died from sepsis, the facility may have neglected its duties or failed to provide the appropriate level of care.</p>",

"Fractures" => "<p>The incidence of fractures of the hip, forearm, vertebra, humerus, pelvis, and ankle increases with advancing age, but rises particularly rapidly after the age of 75 years according to a 2001 study published in the Age and Ageing journal.  According to the Mayo Clinic, the reason for this is that as people age, bones tend to weaken (osteoporosis).   </p>

<p>Hip fractures are the most common fragility fractures needing surgery according to a 2011 study published in the Archives of Orthopaedic and Trauma Surgery.  The Center for Disease Control (<abbr>CDC</abbr>) reports that each year at least 250,000 older people (age 65+) are hospitalized for hip fractures.  In nursing home residents surviving 100 days or more in a facility, the incidence of hip fracture is high (3.7%), particularly among older white, Native American, and newly admitted residents according to a 2016 study published in The Journals of Gerontology.</p>

<p>More than 95% of hip fractures are caused by falling, usually by falling sideways according to the <abbr>CDC</abbr>.  Accordingly, prevention of fractures (esp. hip fractures) must involve strategies aimed at preventing falls.  Within the long-term care environment, fall hazards include wet floors, poor lighting, incorrect bed height, improperly fitted wheelchairs, poor foot care, poorly fitting shoes, improper or incorrect use of walking aids, inattentive staff, and low staff-to-resident ratios.  The law requires facilities to examine risk factors and take steps to limit such risks by keeping the resident environment as free of accident hazards as is possible, giving each resident adequate supervision, and using assistive devices to prevent accidents (42 CFR 483.25(h)).  But facilities must be proactive in order to do so successfully.</p>

<p>If your loved one has suffered a fracture (esp. a hip fracture) at a long-term care facility, it may be a sign that the nursing staff breached the standard of care.</p>",

"Unexplained Injuries " => "<p>The law is not dismissive of unexplained injuries—quite the opposite, especially in cases of mental and physical abuse.  Florida law specifically requires nursing homes to prevent mental and physical abuse of residents in addition to the requirement that all residents be treated courteously, fairly, and with the fullest measure of dignity. The law further requires that residents be provided adequate and appropriate healthcare and protective and support services (Fla. Stat. 400.022(1)(l), (n)-(o).  The word “prevent” simply means to keep (something) from happening or arising.  This particular word sets a high standard of care with respect to resident abuse because mental and physical abuse can be identified even when the abuser(s) is unknown (by bites, cuts, bruises, swollen or tender limbs, fear of a particular person, depression, hostility, stress, apathy, hopelessness, etc.).  Therefore, a nursing home may be held accountable for resident abuse even when the abuser(s) is unknown.  Florida law is not as exacting on assisted living facilities with respect to the wording of the statute, but ALF residents still have the right to live in a safe environment, free from abuse and neglect and be treated with consideration and respect and with due recognition of personal dignity, individuality, and the need for privacy (Fla. Stat. 429.28(b)-(c).</p>

<p>If your loved one has suffered, been hospitalized or died from an unexplained injury or a form of abuse, the facility may be liable for providing substandard care even in the absence of an identifiable cause or abusive individual.</p>"
);
?>
      <ul class="items definitions">
<?php
$count = 0;
foreach($situations as $situation => $definition):
  $count++;
  /* Don't need this anymore since we have definitions.
  if ($definition == "")
    $definition = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam urna urna, pretium eu pretium in, dictum nec nisl. Proin vehicula convallis mi, in vestibulum magna laoreet eget. Duis quis dignissim nibh, at aliquet elit. Mauris ultrices a sapien quis hendrerit. Pellentesque in nisi dui. Pellentesque commodo diam sapien, eget egestas elit rutrum sodales. Etiam sapien nisi, pretium eu consequat ut, sollicitudin vitae erat.";
  */?>
         <li class="list__item <?= str_replace(array(' ', '&amp;'), array('-', ''), $situation) ?>" >
          <button class="btn active list-def" data-gk-close-span-glyph="active" data-gk-open-span-glyph="closed" data-gk-open-class="<?= $count ?>" data-gk-area-state="closed"><?= $situation ?></button>
          <div class="response-definition <?= $count ?>">
            <?= $definition ?>
            <?= $contact_our_office ?>
          </div>
        </li>
  <?php endforeach; ?>
      </ul>
