# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  delapiedralawfirm.dev:
    site_hosts:
      - delapiedralawfirm.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: mike@mzoo.org
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
